### PR TITLE
Cleanup README

### PR DESCRIPTION
**Pull request by NoozAbooz**

### CODE REVIEW

**Review by therealsimon14 — APPROVED** [review]
good

**Review by leha-code — COMMENTED** [review]
bruh another  readme pr cant you do anything else except readmes?

**Comment by NoozAbooz** [comment]
> bruh another readme pr cant you do anything else except readmes?

Yikes man I just got here 5 minutes ago, you want me to also write the client and automate the app creation pipeline?

**Comment by leha-code** [comment]
thats what i expect contributors to do

**Comment by therealsimon14** [comment]
> > bruh another readme pr cant you do anything else except readmes?
> 
> Yikes man I just got here 5 minutes ago, you want me to also write the client and automate the app creation pipeline?

its fine, ignore @leha-code

**Comment by NoozAbooz** [comment]
> thats what i expect contributors to do

Or how about instead of being a stereotypical corporate manager, you do some work yourself? Not everyone has the time and motivation to work on a project, and being negative about that is not appropriate behaviour for any kind of manager, from the CEO of Google to the developers of Rust. Encourage all small contributions, not just the big ones and have others do the work for you.

**Comment by leha-code** [comment]
1. lets take  it to dms
2. lets take it to dms

**Comment by therealsimon14** [comment]
> > thats what i expect contributors to do
> 
> Or how about instead of being a stereotypical corporate manager, you do some work yourself? Not everyone has the time and motivation to work on a project, and being negative about that is not appropriate behaviour for any kind of manager, from the CEO of Google to the developers of Rust. Encourage all small contributions, not just the big ones and have others do the work for you.

Its ok, just dont get into an argument.

**Pull request merged**
