### PR TITLE
Add LineRider Game Request

### PR DESCRIPTION
**Pull request by Sussy-OS**
So, I made this game with two other people, and I *really* wanted to add it. I have tested it on some Ubuntu distros, and Debian, and Raspberry Pi OS, and it works so far.

### CODE REVIEW

**Comment by Sussy-OS** [comment]
@atwoyearold14 I'm pinging you, so you can look at this.

**Comment by leha-code** [comment]
looks great 4 me

**Comment by leha-code** [comment]
merged as it is unstable

**Comment by Sussy-OS** [comment]
Okay, thanks, @leha-code ! (I already had admin perms, but Banana 1.0 told me to not push it myself, and to see if it works for somebody else.)

**Comment by leha-code** [comment]
It is ok to merge it into unstable, because you get it, it might or might not work, thats why it is unstable

**Comment by therealsimon14** [comment]
@Sussy-OS Yes Leha is right

**Pull request merged**
